/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package using.gson;

import com.google.gson.Gson;

import java.io.*;
import java.net.HttpURLConnection;
import java.net.URL;
import java.util.ArrayList;

public class App {
    public static void main(String[] args) {

        ArrayList<Qoute> quoteList = new ArrayList<>();
        quoteList = getQuotesFromJSON(quoteList);
        addToJSON(quoteList,getQuoteFromAPI());
//        addToJSON(quoteList,getQuoteFromAPI());
//        System.out.println(getQuoteFromAPI());
    }

    public static ArrayList<Qoute> getQuotesFromJSON(ArrayList<Qoute> quoteList){
        Gson gson = new Gson();
        String path = "/mnt/Ubuntu_Data/CodeFellows/Labs/java/using-gson/app/src/main/resources/quotes.json";
        File file = new File(path);
        FileReader reader = null;

        try
        {
            reader = new FileReader(file);
        }
        catch(FileNotFoundException c){c.printStackTrace();}
        assert reader != null;
        Qoute[] qoutes = gson.fromJson(reader, Qoute[].class);
        int max = qoutes.length;
        int rand = (int)(Math.random()* max);
        for(Qoute q:qoutes){
            if(q != null)
                quoteList.add(q);
        }
        return quoteList;

    }

    public static Qoute getQuoteFromAPI(){
        Gson gson = new Gson();
        String jsonLine = "";
        try{
            String programmerURL = "http://quotes.stormconsultancy.co.uk/popular.json";
            URL url = new URL(programmerURL);
            HttpURLConnection connection = (HttpURLConnection) url.openConnection();
            connection.setRequestMethod("GET");

            InputStreamReader inputStreamReader = new InputStreamReader(connection.getInputStream());
            BufferedReader bufferedReader = new BufferedReader(inputStreamReader);
            jsonLine = bufferedReader.readLine();
        }catch(IOException e)
        {
            e.printStackTrace();
        }

        Qoute[] results = gson.fromJson(jsonLine,Qoute[].class);
        int randomNum = (int)(Math.random() * results.length);
        Qoute randomQuote = results[randomNum];
        System.out.println(randomQuote.toString());
        return randomQuote;
    }


    public static void addToJSON(ArrayList<Qoute> quoteList,Qoute qoute){
        Gson gson = new Gson();
        String newPath = "/mnt/Ubuntu_Data/CodeFellows/Labs/java/using-gson/app/src/main/resources/miniQuotes.json";
        File file = new File(newPath );
        quoteList.add(qoute);
        FileWriter fileWriter = null;
        try{
            fileWriter = new FileWriter(file);
            gson.toJson(quoteList, fileWriter);
            fileWriter.close();
        }catch(IOException e)
        {
            e.printStackTrace();
        }

    }


}
