/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package using.gson;


import org.junit.Test;

import java.io.IOException;

//import java.io.FileNotFoundException;

public class AppTest {
    @Test
    public void testRandomQuote() throws IOException {
//        String expected = App.getQuoteFromAPI();
//        String actual = App.getQuoteFromAPI();
//        boolean isRandom = expected != actual;
        System.out.println(App.getQuoteFromAPI());
//        System.out.println(App.getQuoteFromAPI());
//
//        assertTrue("Should generate a random quote",isRandom);
    }

}
